name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Cache tikz
        id: cache-tikz
        uses: actions/cache@v2
        with:
          path: figures
          key: ${{ runner.os }}-primes
          
      - name: run latex     
        uses: dante-ev/latex-action@latest
        with:
          root_file: Spectroscopy.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -latexoption=-shell-escape
          
      - name: debug
        run: |
         ls -la
                    
      - name: commit     
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Recompile latex to pdf
            file_pattern: Spectroscopy.pdf figures/*.pdf
          
