name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: make dirs
        run: |
          mkdir figures
          mkdir figures/1_fundamentals
          mkdir figures/1_fundamentals/1_absorption
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: Spectroscopy.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
          
